# Generated by Django 6.0 on 2025-12-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phoneNumber', models.CharField(max_length=200)),
                ('emailAddress', models.CharField(max_length=200)),
            ],
        ),
    ]
